# Generated by Django 3.1.2 on 2020-10-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kala', models.CharField(max_length=50)),
                ('tedad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Famil', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('Type_Car', models.CharField(max_length=50)),
                ('Number_Car', models.CharField(max_length=50)),
                ('Plak_Car', models.CharField(max_length=50)),
                ('Model_Car', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='FirstBazdid',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.car')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shisheh', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('chragh_jelo', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('chragh_aghab', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('chragh_rahnama', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('arm', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('lastik', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('camarband', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('tormoz', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('tormoz_dasti', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('bogh', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('barf', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('ayneh_rast', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('ayneh_chap', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('bogh_aghab', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('sensor', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('khamoshkon', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('box_komak', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('parcham', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('chragh_gardon', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
                ('zanjir', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد')], default='SA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MonthBazdid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chragh_jolo_rahnama', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('chragh_khatar', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('shisheh', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('barf', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('shisheh_shoo', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('bogh', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('sandali', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('charkh', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('lastik', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('tormoz', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('tormoz_dasti', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('bedeneh_darb', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('nezafat', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('motor_girbox', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('parcham', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('chragh_gardon', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('sensor', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('roghan', models.CharField(choices=[('SA', 'سالم'), ('MA', 'معیوب'), ('DA', 'دارد'), ('NA', 'ندارد'), ('TA', 'تعویض شد')], default='SA', max_length=2)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
            ],
        ),
    ]
